#!/bin/bash
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $thisdir
#
# Tarballs and their url's
#
ims_ball="IMS_v0.9.2.1.tar.gz"
ims_urldir="http://www.comp.nus.edu.sg/~nlp/sw"
# ims_second_urldir="http://kyoto.let.vu.nl~/newsreader/it_makes_sense_WSD"
ims_second_urldir="http://kyoto.let.vu.nl/nlpp_repo/it_makes_sense_WSD"
ims_lib_ball="lib.tar.gz"
#ims_lib_urldir="http://www.comp.nus.edu.sg/~nlp/sw"
ims_models_ball="models.tar.gz"
alt_ims_models_ball="20181023_models.tar.gz"
wordnet_version="1.7.1"
wordnet_urldir="http://wordnetcode.princeton.edu/${wordnet_version}"
wordnet_ball="WordNet-${wordnet_version}.tar.gz"

# Note: it is not always possible to download the models from their proper location. Therefore,
# as a hack, download the models from a secret storage using a secret key.

function get_and_unpack_ball () {
    url_dir=$1
    second_url_dir=$2
    ball=$3
    wget ${url_dir}/${ball}
    result=$?
    if
       [ $result -gt 0 ]
    then
       wget ${second_url_dir}/${ball}
       result=$?
    fi
    if
       [ $result == 0 ]
    then
	tar -xzf ${ball}
	rm ${ball}
    else
	echo "Cannot download $ball"
    fi
}


# For the main package

get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_ball}
mv ims_0.9.2.1 ims

# For the library
cd ${thisdir}/ims
chmod +x testPlain.bash
get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_lib_ball}

# For the models
# get_and_unpack_ball ${ims_urldir} ${ims_second_urldir} ${ims_models_ball}
wget ${ims_second_urldir}/${alt_ims_models_ball}
result=$?
if
   [ $result -gt 0 ]
then
    echo "Cannot download from ${ims_second_url_dir}/${alt_ims_models_ball}"
else
    tar -xzf ${alt_ims_models_ball}
    rm ${alt_ims_models_ball}
fi



cd ${thisdir}

# TODO: find solution for path_to_ims.py.

# Temporary solution while url http://nlp.lsi.upc.edu/tools/download-map.php is broken.

wget http://kyoto.let.vu.nl/nlpp_repo/it_makes_sense_WSD/ims_resources.tgz
tar -xzf ims_resources.tgz
rm ims_resources.tgz

#mkdir resources
#cd resources
#
##For WordNet171
#get_and_unpack_ball ${wordnet_urldir} ${wordnet_ball}
#
##For the mappings between wn versions
#wget -O mappings.tgz http://nlp.lsi.upc.edu/tools/download-map.php
#tar xzf mappings.tgz
# mv mappings-upc-2007/ mappings-upc
#rm mappings.tgz

cd ${thisdir}

#For the KafNafPArserPy
pip install KafNafParserPy
